In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

Read the 2 tables

In [3]:
path2covid_data = "/home/bcrlab/igguest/porat_naama/data/raw/geographic-sum-per-day-ver_00859.csv"
path2mifkad = "/home/bcrlab/igguest/porat_naama/data/raw/mifkad 2022.csv"

covid_data = pd.read_csv(path2covid_data)
mifkad_data = pd.read_csv(path2mifkad)

Covid data- pre:

In [4]:
covid_data.head(5)

,town_code,agas_code,town,date,accumulated_cases,new_cases_on_date,accumulated_recoveries,new_recoveries_on_date,accumulated_hospitalized,new_hospitalized_on_date,accumulated_deaths,new_deaths_on_date,accumulated_diagnostic_tests,new_diagnostic_tests_on_date,accumulated_vaccination_first_dose,new_vacc_first_dose_on_date,accumulated_vaccination_second_dose,new_vacc_second_dose_on_date,accumulated_vaccination_third_dose,new_vacc_third_dose_on_date
0,26,NaN,ראש פינה,2020-03-11,0,False,0,False,0.0,False,0,False,0,False,0.0,False,0.0,False,0.0,False
1,26,NaN,ראש פינה,2020-03-12,0,False,0,False,0.0,False,0,False,0,False,0.0,False,0.0,False,0.0,False
2,26,NaN,ראש פינה,2020-03-13,0,False,0,False,0.0,False,0,False,0,False,0.0,False,0.0,False,0.0,False
3,26,NaN,ראש פינה,2020-03-14,0,False,0,False,0.0,False,0,False,0,False,0.0,False,0.0,False,0.0,False
4,26,NaN,ראש פינה,2020-03-15,0,False,0,False,0.0,False,0,False,0,False,0.0,False,0.0,False,0.0,False

In [5]:
covid_data.replace('<15', 7, inplace=True)
print((covid_data == '<15').any().any())
covid_data = covid_data.fillna(0)
covid_data.head()

False

,town_code,agas_code,town,date,accumulated_cases,new_cases_on_date,accumulated_recoveries,new_recoveries_on_date,accumulated_hospitalized,new_hospitalized_on_date,accumulated_deaths,new_deaths_on_date,accumulated_diagnostic_tests,new_diagnostic_tests_on_date,accumulated_vaccination_first_dose,new_vacc_first_dose_on_date,accumulated_vaccination_second_dose,new_vacc_second_dose_on_date,accumulated_vaccination_third_dose,new_vacc_third_dose_on_date
0,26,0.0,ראש פינה,2020-03-11,0,False,0,False,0.0,False,0,False,0,False,0.0,False,0.0,False,0.0,False
1,26,0.0,ראש פינה,2020-03-12,0,False,0,False,0.0,False,0,False,0,False,0.0,False,0.0,False,0.0,False
2,26,0.0,ראש פינה,2020-03-13,0,False,0,False,0.0,False,0,False,0,False,0.0,False,0.0,False,0.0,False
3,26,0.0,ראש פינה,2020-03-14,0,False,0,False,0.0,False,0,False,0,False,0.0,False,0.0,False,0.0,False
4,26,0.0,ראש פינה,2020-03-15,0,False,0,False,0.0,False,0,False,0,False,0.0,False,0.0,False,0.0,False

In [6]:
covid_data['agas_code'] = covid_data['agas_code'].astype(int)
covid_data['City_agas_code'] = covid_data['town_code'].astype(str) + "_" + covid_data['agas_code'].astype(str)
covid_data = covid_data.set_index('City_agas_code')

covid_data.head()

,town_code,agas_code,town,date,accumulated_cases,new_cases_on_date,accumulated_recoveries,new_recoveries_on_date,accumulated_hospitalized,new_hospitalized_on_date,accumulated_deaths,new_deaths_on_date,accumulated_diagnostic_tests,new_diagnostic_tests_on_date,accumulated_vaccination_first_dose,new_vacc_first_dose_on_date,accumulated_vaccination_second_dose,new_vacc_second_dose_on_date,accumulated_vaccination_third_dose,new_vacc_third_dose_on_date
City_agas_code,,,,,,,,,,,,,,,,,,,,
26_0,26,0,ראש פינה,2020-03-11,0,False,0,False,0.0,False,0,False,0,False,0.0,False,0.0,False,0.0,False
26_0,26,0,ראש פינה,2020-03-12,0,False,0,False,0.0,False,0,False,0,False,0.0,False,0.0,False,0.0,False
26_0,26,0,ראש פינה,2020-03-13,0,False,0,False,0.0,False,0,False,0,False,0.0,False,0.0,False,0.0,False
26_0,26,0,ראש פינה,2020-03-14,0,False,0,False,0.0,False,0,False,0,False,0.0,False,0.0,False,0.0,False
26_0,26,0,ראש פינה,2020-03-15,0,False,0,False,0.0,False,0,False,0,False,0.0,False,0.0,False,0.0,False

In [7]:
covid_data = covid_data.drop(columns=['town_code','agas_code'])
covid_data = covid_data.sort_values(['City_agas_code', 'date'])
covid_data.head()

,town,date,accumulated_cases,new_cases_on_date,accumulated_recoveries,new_recoveries_on_date,accumulated_hospitalized,new_hospitalized_on_date,accumulated_deaths,new_deaths_on_date,accumulated_diagnostic_tests,new_diagnostic_tests_on_date,accumulated_vaccination_first_dose,new_vacc_first_dose_on_date,accumulated_vaccination_second_dose,new_vacc_second_dose_on_date,accumulated_vaccination_third_dose,new_vacc_third_dose_on_date
City_agas_code,,,,,,,,,,,,,,,,,,
1015_0,מבשרת ציון,2020-03-11,0,False,0,False,0.0,False,0,False,0,False,0.0,False,0.0,False,0.0,False
1015_0,מבשרת ציון,2020-03-12,0,False,0,False,0.0,False,0,False,7,True,0.0,False,0.0,False,0.0,False
1015_0,מבשרת ציון,2020-03-13,0,False,0,False,0.0,False,0,False,7,False,0.0,False,0.0,False,0.0,False
1015_0,מבשרת ציון,2020-03-14,0,False,0,False,0.0,False,0,False,7,False,0.0,False,0.0,False,0.0,False
1015_0,מבשרת ציון,2020-03-15,0,False,0,False,0.0,False,0,False,7,False,0.0,False,0.0,False,0.0,False