In [1]:
# scripts/01_preprocessing.ipynb

from pathlib import Path
import pandas as pd
import numpy as np

RAW_PATH = Path("/home/bcrlab/igguest/porat_naama/data/raw/geographic-sum-per-day-ver_00859.csv")
OUT_PATH = Path("/home/bcrlab/igguest/porat_naama/data/processed/covid_clean.parquet")

df_loc_corona = pd.read_csv(RAW_PATH).copy()
(df_loc_corona == '<15').any().any()

True

In [2]:
df_loc_corona.replace('<15', 7, inplace=True)
print((df_loc_corona == '<15').any().any())
df_loc_corona = df_loc_corona.fillna(0)
df_loc_corona.head()

False

,town_code,agas_code,town,date,accumulated_cases,new_cases_on_date,accumulated_recoveries,new_recoveries_on_date,accumulated_hospitalized,new_hospitalized_on_date,accumulated_deaths,new_deaths_on_date,accumulated_diagnostic_tests,new_diagnostic_tests_on_date,accumulated_vaccination_first_dose,new_vacc_first_dose_on_date,accumulated_vaccination_second_dose,new_vacc_second_dose_on_date,accumulated_vaccination_third_dose,new_vacc_third_dose_on_date
0,26,0.0,ראש פינה,2020-03-11,0,False,0,False,0.0,False,0,False,0,False,0.0,False,0.0,False,0.0,False
1,26,0.0,ראש פינה,2020-03-12,0,False,0,False,0.0,False,0,False,0,False,0.0,False,0.0,False,0.0,False
2,26,0.0,ראש פינה,2020-03-13,0,False,0,False,0.0,False,0,False,0,False,0.0,False,0.0,False,0.0,False
3,26,0.0,ראש פינה,2020-03-14,0,False,0,False,0.0,False,0,False,0,False,0.0,False,0.0,False,0.0,False
4,26,0.0,ראש פינה,2020-03-15,0,False,0,False,0.0,False,0,False,0,False,0.0,False,0.0,False,0.0,False

In [3]:
df_loc_corona['agas_code'] = df_loc_corona['agas_code'].astype(int)
df_loc_corona['City_agas_code'] = df_loc_corona['town_code'].astype(str) + "_" + df_loc_corona['agas_code'].astype(str)
df_loc_corona = df_loc_corona.set_index('City_agas_code')

df_loc_corona.head()

,town_code,agas_code,town,date,accumulated_cases,new_cases_on_date,accumulated_recoveries,new_recoveries_on_date,accumulated_hospitalized,new_hospitalized_on_date,accumulated_deaths,new_deaths_on_date,accumulated_diagnostic_tests,new_diagnostic_tests_on_date,accumulated_vaccination_first_dose,new_vacc_first_dose_on_date,accumulated_vaccination_second_dose,new_vacc_second_dose_on_date,accumulated_vaccination_third_dose,new_vacc_third_dose_on_date
City_agas_code,,,,,,,,,,,,,,,,,,,,
26_0,26,0,ראש פינה,2020-03-11,0,False,0,False,0.0,False,0,False,0,False,0.0,False,0.0,False,0.0,False
26_0,26,0,ראש פינה,2020-03-12,0,False,0,False,0.0,False,0,False,0,False,0.0,False,0.0,False,0.0,False
26_0,26,0,ראש פינה,2020-03-13,0,False,0,False,0.0,False,0,False,0,False,0.0,False,0.0,False,0.0,False
26_0,26,0,ראש פינה,2020-03-14,0,False,0,False,0.0,False,0,False,0,False,0.0,False,0.0,False,0.0,False
26_0,26,0,ראש פינה,2020-03-15,0,False,0,False,0.0,False,0,False,0,False,0.0,False,0.0,False,0.0,False

In [4]:
df_loc_corona = df_loc_corona.drop(columns=['new_cases_on_date', 'new_recoveries_on_date', 'new_hospitalized_on_date', 'new_deaths_on_date', 'new_diagnostic_tests_on_date', 'new_vacc_first_dose_on_date', 'new_vacc_second_dose_on_date', 'new_vacc_third_dose_on_date'])
df_loc_corona = df_loc_corona.drop(columns=['town_code','agas_code'])
df_loc_corona = df_loc_corona.sort_values(['City_agas_code', 'date'])
df_loc_corona.head()

,town,date,accumulated_cases,accumulated_recoveries,accumulated_hospitalized,accumulated_deaths,accumulated_diagnostic_tests,accumulated_vaccination_first_dose,accumulated_vaccination_second_dose,accumulated_vaccination_third_dose
City_agas_code,,,,,,,,,,
1015_0,מבשרת ציון,2020-03-11,0,0,0.0,0,0,0.0,0.0,0.0
1015_0,מבשרת ציון,2020-03-12,0,0,0.0,0,7,0.0,0.0,0.0
1015_0,מבשרת ציון,2020-03-13,0,0,0.0,0,7,0.0,0.0,0.0
1015_0,מבשרת ציון,2020-03-14,0,0,0.0,0,7,0.0,0.0,0.0
1015_0,מבשרת ציון,2020-03-15,0,0,0.0,0,7,0.0,0.0,0.0

In [5]:
columns_to_convert = ['accumulated_cases', 'accumulated_recoveries', 'accumulated_hospitalized', 'accumulated_deaths', 'accumulated_diagnostic_tests', 'accumulated_vaccination_first_dose', 'accumulated_vaccination_second_dose', 'accumulated_vaccination_third_dose']
for column in columns_to_convert:
    # Convert to numeric first, then cast to integer
    df_loc_corona[column] = pd.to_numeric(df_loc_corona[column], errors='coerce').fillna(0).astype(int)
df_loc_corona.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1942906 entries, 1015_0 to 99_0
Data columns (total 10 columns):
 #   Column                               Dtype
---  ------                               -----
 0   town                                 object
 1   date                                 object
 2   accumulated_cases                    int64
 3   accumulated_recoveries               int64
 4   accumulated_hospitalized             int64
 5   accumulated_deaths                   int64
 6   accumulated_diagnostic_tests         int64
 7   accumulated_vaccination_first_dose   int64
 8   accumulated_vaccination_second_dose  int64
 9   accumulated_vaccination_third_dose   int64
dtypes: int64(8), object(2)
memory usage: 163.1+ MB

In [6]:

df_loc_corona = df_loc_corona.copy()

# (also important: sort before diff)
df_loc_corona = df_loc_corona.sort_values(["City_agas_code", "date"])

df_loc_corona["positive_daily"]      = df_loc_corona.groupby("City_agas_code")["accumulated_cases"].diff()
df_loc_corona["hospitalized_daily"]  = df_loc_corona.groupby("City_agas_code")["accumulated_hospitalized"].diff()
df_loc_corona["tested_daily"]        = df_loc_corona.groupby("City_agas_code")["accumulated_diagnostic_tests"].diff()

df_loc_corona["infection_rate"]   = df_loc_corona["positive_daily"] / df_loc_corona["tested_daily"]
df_loc_corona["recovery_ratio"]   = df_loc_corona["accumulated_recoveries"] / df_loc_corona["accumulated_cases"]
df_loc_corona["recovery_index"]   = df_loc_corona["accumulated_recoveries"] / df_loc_corona["accumulated_diagnostic_tests"]

# Replace inf/-inf -> NaN, then decide how to fill
df_loc_corona["infection_rate"] = df_loc_corona["infection_rate"].replace([np.inf, -np.inf], np.nan)

# Now choose fill policy
df_loc_corona = df_loc_corona.fillna(0)
df_loc_corona.tail()

,town,date,accumulated_cases,accumulated_recoveries,accumulated_hospitalized,accumulated_deaths,accumulated_diagnostic_tests,accumulated_vaccination_first_dose,accumulated_vaccination_second_dose,accumulated_vaccination_third_dose,positive_daily,hospitalized_daily,tested_daily,infection_rate,recovery_ratio,recovery_index
City_agas_code,,,,,,,,,,,,,,,,
99_0,מצפה רמון,2023-05-24,2676,2666,34,7,32481,3545,3323,2521,0.0,0.0,0.0,0.0,0.996263,0.082079
99_0,מצפה רמון,2023-05-25,2676,2666,34,7,32481,3545,3323,2521,0.0,0.0,0.0,0.0,0.996263,0.082079
99_0,מצפה רמון,2023-05-26,2676,2666,34,7,32481,3545,3323,2521,0.0,0.0,0.0,0.0,0.996263,0.082079
99_0,מצפה רמון,2023-05-27,2676,2666,34,7,32482,3545,3323,2521,0.0,0.0,1.0,0.0,0.996263,0.082076
99_0,מצפה רמון,2023-05-28,2676,2666,34,7,32482,3545,3323,2521,0.0,0.0,0.0,0.0,0.996263,0.082076

In [7]:
df_loc_corona['is_lockdown'] = 0
df_loc_corona['date']= pd.to_datetime(df_loc_corona['date'])
df_loc_corona.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1942906 entries, 1015_0 to 99_0
Data columns (total 17 columns):
 #   Column                               Dtype
---  ------                               -----
 0   town                                 object
 1   date                                 datetime64[ns]
 2   accumulated_cases                    int64
 3   accumulated_recoveries               int64
 4   accumulated_hospitalized             int64
 5   accumulated_deaths                   int64
 6   accumulated_diagnostic_tests         int64
 7   accumulated_vaccination_first_dose   int64
 8   accumulated_vaccination_second_dose  int64
 9   accumulated_vaccination_third_dose   int64
 10  positive_daily                       float64
 11  hospitalized_daily                   float64
 12  tested_daily                         float64
 13  infection_rate                       float64
 14  recovery_ratio                       float64
 15  recovery_index                       float64
 16  is_lockdown                          int64
dtypes: datetime64[ns](1), float64(6), int64(9), object(1)
memory usage: 266.8+ MB

In [8]:
#lockdown dates:
#March 19, 2020 – April 24, 2020
#September 18, 2020 – October 18, 2020
#December 27, 2020 – February 6, 2021
#July 29, 2021 – November 27, 2021

lockdown_periods = [('2020-03-19', '2020-04-24'), ('2020-09-18', '2020-10-18'), ('2020-12-27', '2021-02-06'), ('2021-07-29', '2021-11-27')]

lockdown_periods = [(pd.Timestamp(start), pd.Timestamp(end)) for start, end in lockdown_periods]


for start_date, end_date in lockdown_periods:
    mask = (df_loc_corona['date'] >= start_date) & (df_loc_corona['date'] <= end_date)
    df_loc_corona.loc[mask, 'is_lockdown'] = 1

df_loc_corona.tail()

,town,date,accumulated_cases,accumulated_recoveries,accumulated_hospitalized,accumulated_deaths,accumulated_diagnostic_tests,accumulated_vaccination_first_dose,accumulated_vaccination_second_dose,accumulated_vaccination_third_dose,positive_daily,hospitalized_daily,tested_daily,infection_rate,recovery_ratio,recovery_index,is_lockdown
City_agas_code,,,,,,,,,,,,,,,,,
99_0,מצפה רמון,2023-05-24,2676,2666,34,7,32481,3545,3323,2521,0.0,0.0,0.0,0.0,0.996263,0.082079,0
99_0,מצפה רמון,2023-05-25,2676,2666,34,7,32481,3545,3323,2521,0.0,0.0,0.0,0.0,0.996263,0.082079,0
99_0,מצפה רמון,2023-05-26,2676,2666,34,7,32481,3545,3323,2521,0.0,0.0,0.0,0.0,0.996263,0.082079,0
99_0,מצפה רמון,2023-05-27,2676,2666,34,7,32482,3545,3323,2521,0.0,0.0,1.0,0.0,0.996263,0.082076,0
99_0,מצפה רמון,2023-05-28,2676,2666,34,7,32482,3545,3323,2521,0.0,0.0,0.0,0.0,0.996263,0.082076,0

In [9]:
df_loc_corona[df_loc_corona['date']=='2020-03-19'].head()

,town,date,accumulated_cases,accumulated_recoveries,accumulated_hospitalized,accumulated_deaths,accumulated_diagnostic_tests,accumulated_vaccination_first_dose,accumulated_vaccination_second_dose,accumulated_vaccination_third_dose,positive_daily,hospitalized_daily,tested_daily,infection_rate,recovery_ratio,recovery_index,is_lockdown
City_agas_code,,,,,,,,,,,,,,,,,
1015_0,מבשרת ציון,2020-03-19,0,0,0,0,7,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1
1015_1,מבשרת ציון,2020-03-19,0,0,0,0,7,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1
1015_2,מבשרת ציון,2020-03-19,0,0,0,0,7,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1
1015_3,מבשרת ציון,2020-03-19,0,0,0,0,18,0,0,0,0.0,0.0,11.0,0.0,0.0,0.0,1
1015_4,מבשרת ציון,2020-03-19,0,0,0,0,7,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [20]:
df_loc_corona.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1942906 entries, 1015_0 to 99_0
Data columns (total 17 columns):
 #   Column                               Dtype
---  ------                               -----
 0   town                                 object
 1   date                                 datetime64[ns]
 2   accumulated_cases                    int64
 3   accumulated_recoveries               int64
 4   accumulated_hospitalized             int64
 5   accumulated_deaths                   int64
 6   accumulated_diagnostic_tests         int64
 7   accumulated_vaccination_first_dose   int64
 8   accumulated_vaccination_second_dose  int64
 9   accumulated_vaccination_third_dose   int64
 10  positive_daily                       float64
 11  hospitalized_daily                   float64
 12  tested_daily                         float64
 13  infection_rate                       float64
 14  recovery_ratio                       float64
 15  recovery_index                       float64
 16  is_lockdown                          int64
dtypes: datetime64[ns](1), float64(6), int64(9), object(1)
memory usage: 299.1+ MB

In [22]:
df_loc_corona.to_csv("/home/bcrlab/igguest/porat_naama/data/processed/Corona_loc_processed.csv")

print("Saved:", "/home/bcrlab/igguest/porat_naama/data/processed/Corona_loc_processed.csv")

Saved: /home/bcrlab/igguest/porat_naama/data/processed/Corona_loc_processed.csv

In [10]:
import re
import numpy as np
import pandas as pd
from pathlib import Path

Mifkad_RAW_PATH = Path("/home/bcrlab/igguest/porat_naama/data/raw/mifkad_2.csv")

In [11]:
raw_mif_2 = pd.read_csv(Mifkad_RAW_PATH).copy()

raw_mif_2.head()

,OBJECTID,SHEM_YISHUV_HEB,SHEM_YISHUV_ENG,SEMEL_YISHUV,YISHUV_STAT_2022,STAT_2022,Stat2022_Unite,Stat2022_Ref,Main_Function_Code,Main_Function_Txt,...,hh_MidatDatiyut,hh_MidatDatiyut_Name,Computer_avg,Vehicle0_pcnt,Vehicle2up_pcnt,Parking_pcnt,own_pcnt,rent_pcnt,Shape__Area,Shape__Length
0,1,שחר,SHAHAR,7,70001,1.0,1,NaN,1.0,מגורים,...,2.0,מסורתי,1.1,16.9,45.9,88.9,63.3,18.3,2.299948e+06,7470.551048
1,2,תירוש,TIROSH,10,100001,1.0,1,NaN,1.0,מגורים,...,3.0,דתי/ דתי מאוד,0.8,26.2,24.2,73.2,45.4,30.5,1.348877e+06,5373.979325
2,3,"ניר ח""ן",NIR HEN,11,110001,1.0,1,NaN,1.0,מגורים,...,1.0,חילוני,1.5,15.7,48.2,76.6,53.6,30.6,8.950495e+05,4668.721712
3,4,חצבה,HAZEVA,13,130001,1.0,1,NaN,1.0,מגורים,...,1.0,חילוני,1.9,11.1,60.7,95.5,63.5,26.9,1.306252e+06,5623.056457
4,5,נועם,NO'AM,15,150001,1.0,1,NaN,1.0,מגורים,...,2.0,מסורתי,0.7,8.2,39.3,82.0,29.5,40.3,1.656053e+06,6987.293605

In [12]:

# Clean key parts
raw_mif_2["SEMEL_YISHUV"] = raw_mif_2["SEMEL_YISHUV"].astype(str).str.strip()
raw_mif_2["STAT_2022"] = pd.to_numeric(raw_mif_2["STAT_2022"], errors="coerce").astype("Int64")

# Localities appearing in exactly one row are not divided into statistical areas -> suffix '0'
loc_counts = raw_mif_2["SEMEL_YISHUV"].value_counts()
is_single_row = raw_mif_2["SEMEL_YISHUV"].map(loc_counts).eq(1)

# Rows with no STAT_2022 also get '0'
suffix = raw_mif_2["STAT_2022"].astype(str)
suffix = suffix.mask(is_single_row | raw_mif_2["STAT_2022"].isna(), "0")

raw_mif_2["City_agas_code"] = raw_mif_2["SEMEL_YISHUV"] + "_" + suffix

print(f"rows:                      {len(raw_mif_2):,}")
print(f"single-row localities:     {is_single_row.sum():,}")
print(f"rows with STAT_2022 = NA:  {raw_mif_2['STAT_2022'].isna().sum():,}")
print(f"keys ending in _0:         {raw_mif_2['City_agas_code'].str.endswith('_0').sum():,}")
print(f"key unique:                {raw_mif_2['City_agas_code'].is_unique}")

# Keep StatAreaCmb in raw_mif_2 for mapping later. No global fillna(0) here.
out_dir = Path("data/outputs")
out_dir.mkdir(parents=True, exist_ok=True)
raw_mif_2.to_csv(out_dir / "raw_mif_2_inspect.csv", index=False, encoding="utf-8-sig")

out_dir = Path("data/outputs")
out_dir.mkdir(parents=True, exist_ok=True)


raw_mif_2 = raw_mif_2.set_index("City_agas_code")
raw_mif_2.head()

raw_mif_2_csv = out_dir / "raw_mif_2_inspect.csv"
raw_mif_2.to_csv(raw_mif_2_csv, index=False)



raw_mif_2.head()

rows:                      3,857
single-row localities:     1,242
rows with STAT_2022 = NA:  104
keys ending in _0:         1,242
key unique:                True

,OBJECTID,SHEM_YISHUV_HEB,SHEM_YISHUV_ENG,SEMEL_YISHUV,YISHUV_STAT_2022,STAT_2022,Stat2022_Unite,Stat2022_Ref,Main_Function_Code,Main_Function_Txt,...,hh_MidatDatiyut,hh_MidatDatiyut_Name,Computer_avg,Vehicle0_pcnt,Vehicle2up_pcnt,Parking_pcnt,own_pcnt,rent_pcnt,Shape__Area,Shape__Length
City_agas_code,,,,,,,,,,,,,,,,,,,,,
7_0,1,שחר,SHAHAR,7,70001,1,1,NaN,1.0,מגורים,...,2.0,מסורתי,1.1,16.9,45.9,88.9,63.3,18.3,2.299948e+06,7470.551048
10_0,2,תירוש,TIROSH,10,100001,1,1,NaN,1.0,מגורים,...,3.0,דתי/ דתי מאוד,0.8,26.2,24.2,73.2,45.4,30.5,1.348877e+06,5373.979325
11_0,3,"ניר ח""ן",NIR HEN,11,110001,1,1,NaN,1.0,מגורים,...,1.0,חילוני,1.5,15.7,48.2,76.6,53.6,30.6,8.950495e+05,4668.721712
13_0,4,חצבה,HAZEVA,13,130001,1,1,NaN,1.0,מגורים,...,1.0,חילוני,1.9,11.1,60.7,95.5,63.5,26.9,1.306252e+06,5623.056457
15_0,5,נועם,NO'AM,15,150001,1,1,NaN,1.0,מגורים,...,2.0,מסורתי,0.7,8.2,39.3,82.0,29.5,40.3,1.656053e+06,6987.293605

In [13]:
raw_mif_2.head()

,OBJECTID,SHEM_YISHUV_HEB,SHEM_YISHUV_ENG,SEMEL_YISHUV,YISHUV_STAT_2022,STAT_2022,Stat2022_Unite,Stat2022_Ref,Main_Function_Code,Main_Function_Txt,...,hh_MidatDatiyut,hh_MidatDatiyut_Name,Computer_avg,Vehicle0_pcnt,Vehicle2up_pcnt,Parking_pcnt,own_pcnt,rent_pcnt,Shape__Area,Shape__Length
City_agas_code,,,,,,,,,,,,,,,,,,,,,
7_0,1,שחר,SHAHAR,7,70001,1,1,NaN,1.0,מגורים,...,2.0,מסורתי,1.1,16.9,45.9,88.9,63.3,18.3,2.299948e+06,7470.551048
10_0,2,תירוש,TIROSH,10,100001,1,1,NaN,1.0,מגורים,...,3.0,דתי/ דתי מאוד,0.8,26.2,24.2,73.2,45.4,30.5,1.348877e+06,5373.979325
11_0,3,"ניר ח""ן",NIR HEN,11,110001,1,1,NaN,1.0,מגורים,...,1.0,חילוני,1.5,15.7,48.2,76.6,53.6,30.6,8.950495e+05,4668.721712
13_0,4,חצבה,HAZEVA,13,130001,1,1,NaN,1.0,מגורים,...,1.0,חילוני,1.9,11.1,60.7,95.5,63.5,26.9,1.306252e+06,5623.056457
15_0,5,נועם,NO'AM,15,150001,1,1,NaN,1.0,מגורים,...,2.0,מסורתי,0.7,8.2,39.3,82.0,29.5,40.3,1.656053e+06,6987.293605

In [14]:
n_nan_pop_density = raw_mif_2["pop_density"].isna().sum()
print("Rows with NaN pop_density:", n_nan_pop_density)

Rows with NaN pop_density: 2815

In [15]:
raw_mif_2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3857 entries, 7_0 to 3795_0
Data columns (total 70 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   OBJECTID                    3857 non-null   int64
 1   SHEM_YISHUV_HEB             3857 non-null   object
 2   SHEM_YISHUV_ENG             3799 non-null   object
 3   SEMEL_YISHUV                3857 non-null   object
 4   YISHUV_STAT_2022            3857 non-null   int64
 5   STAT_2022                   3753 non-null   Int64
 6   Stat2022_Unite              3235 non-null   object
 7   Stat2022_Ref                240 non-null    float64
 8   Main_Function_Code          3697 non-null   float64
 9   Main_Function_Txt           3697 non-null   object
 10  ROVA                        1420 non-null   float64
 11  TAT_ROVA                    2080 non-null   float64
 12  Religion_Stat_Code          3235 non-null   float64
 13  Religion_Stat_Txt           3235 non-null   object
 14  pop_approx                  3235 non-null   float64
 15  change_pcnt                 1018 non-null   float64
 16  pop_density                 1042 non-null   float64
 17  sexRatio                    3235 non-null   float64
 18  inst_pcnt                   233 non-null    float64
 19  Foreign_pcnt                926 non-null    float64
 20  age0_19_pcnt                3235 non-null   float64
 21  age20_64_pcnt               3235 non-null   float64
 22  age65_pcnt                  3221 non-null   float64
 23  DependencyRatio             3235 non-null   float64
 24  age_median                  3235 non-null   float64
 25  m_age_median                3235 non-null   float64
 26  w_age_median                3235 non-null   float64
 27  married18_34_pcnt           3230 non-null   float64
 28  married45_54_pcnt           3233 non-null   float64
 29  j_isr_pcnt                  2834 non-null   float64
 30  j_abr_pcnt                  2834 non-null   float64
 31  aliya2002_pcnt              2812 non-null   float64
 32  aliya2010_pcnt              2771 non-null   float64
 33  israel_pcnt                 2834 non-null   float64
 34  asia_pcnt                   2833 non-null   float64
 35  africa_pcnt                 2834 non-null   float64
 36  europe_pcnt                 2834 non-null   float64
 37  america_pcnt                2822 non-null   float64
 38  shem_eretz1                 2834 non-null   object
 39  MarriageAge_mdn             3233 non-null   float64
 40  m_MarriageAge_mdn           3233 non-null   float64
 41  w_MarriageAge_mdn           3233 non-null   float64
 42  ChldBorn_avg                3233 non-null   float64
 43  koshi5_pcnt                 3224 non-null   float64
 44  koshi65_pcnt                3090 non-null   float64
 45  AcadmCert_pcnt              3231 non-null   float64
 46  WrkY_pcnt                   3233 non-null   float64
 47  Empl_pcnt                   3233 non-null   float64
 48  SelfEmpl_pcnt               3218 non-null   float64
 49  HrsWrkWk_avg                3233 non-null   float64
 50  Wrk_15_17_pcnt              2971 non-null   float64
 51  WrkOutLoc_pcnt              3231 non-null   float64
 52  employeesAnnual_medWage     3233 non-null   float64
 53  EmployeesWage_decile9Up     3216 non-null   float64
 54  SelfEmployedAnnual_medWage  3208 non-null   float64
 55  SelfEmployedWage_decile9Up  2900 non-null   float64
 56  hh_total_approx             3233 non-null   float64
 57  size_avg                    3233 non-null   float64
 58  hh0_5_pcnt                  3231 non-null   float64
 59  hh18_24_pcnt                3225 non-null   float64
 60  hh_MidatDatiyut             3233 non-null   float64
 61  hh_MidatDatiyut_Name        3233 non-null   object
 62  Computer_avg                3233 non-null   float64
 63  Vehicle0_pcnt               3202 non-null   float64
 64  Vehicle2up_pcnt             3226 non-null   float64
 65  Parking_pcnt                3230 non-null   float64
 66  own_pcnt                    3230 non-null   float64
 67  rent_pcnt                   3217 non-null   float64
 68  Shape__Area                 3857 non-null   float64
 69  Shape__Length               3857 non-null   float64
dtypes: Int64(1), float64(59), int64(2), object(8)
memory usage: 2.1+ MB

In [16]:
raw_mif_2 [raw_mif_2.index == "2600_16"].head()

,OBJECTID,SHEM_YISHUV_HEB,SHEM_YISHUV_ENG,SEMEL_YISHUV,YISHUV_STAT_2022,STAT_2022,Stat2022_Unite,Stat2022_Ref,Main_Function_Code,Main_Function_Txt,...,hh_MidatDatiyut,hh_MidatDatiyut_Name,Computer_avg,Vehicle0_pcnt,Vehicle2up_pcnt,Parking_pcnt,own_pcnt,rent_pcnt,Shape__Area,Shape__Length
City_agas_code,,,,,,,,,,,,,,,,,,,,,
2600_16,2021,אילת,ELAT,2600,26000016,16,16+11+12+17,NaN,1.0,מגורים,...,1.0,חילוני,0.7,56.1,12.9,30.7,35.1,50.6,316681.374405,2490.42347

In [17]:
processed_dir = Path("/home/bcrlab/igguest/porat_naama/data/processed")
processed_dir.mkdir(parents=True, exist_ok=True)

raw_mif_2.to_csv(processed_dir / "Mifkad_2_processed.csv")
df_loc_corona.to_csv(processed_dir / "Corona_loc_processed.csv")

print("Saved:", processed_dir / "Mifkad_2_processed.csv")
print("Saved:", processed_dir / "Corona_loc_processed.csv")

Saved: /home/bcrlab/igguest/porat_naama/data/processed/Mifkad_2_processed.csv
Saved: /home/bcrlab/igguest/porat_naama/data/processed/Corona_loc_processed.csv

In [18]:
df_corona = pd.read_csv('/home/bcrlab/igguest/porat_naama/data/processed/Corona_loc_processed.csv', dtype={'City_agas_code': str})
df_mifkad = pd.read_csv('/home/bcrlab/igguest/porat_naama/data/processed/Mifkad_2_processed.csv',      dtype={'City_agas_code': str})

assert df_mifkad['City_agas_code'].is_unique, 'Mifkad key is not unique - merge would explode rows'
n_before = len(df_corona)

df_corona_merged = df_corona.merge(
    df_mifkad.drop(columns=['OBJECTID', 'SHEM_YISHUV_HEB', 'SEMEL_YISHUV', 'YISHUV_STAT_2022', 'STAT_2022', 'Stat2022_Unite', 'Stat2022_Ref']),
    on='City_agas_code',
    how='left',
    validate='many_to_one'
)
assert len(df_corona_merged) == n_before, 'Row count changed - unexpected duplication'

matched = df_corona_merged['pop'].notna()
keys_all = df_corona['City_agas_code'].unique()
keys_unmatched = sorted(set(keys_all) - set(df_mifkad['City_agas_code']))

print(f'rows:            {n_before:,} -> {len(df_corona_merged):,}')
print(f'rows matched:    {matched.sum():,} ({100*matched.mean():.1f}%)')
print(f'keys matched:    {len(keys_all)-len(keys_unmatched)} / {len(keys_all)}')
print(f'keys unmatched:  {len(keys_unmatched)}')

df_corona_merged['has_census'] = matched.astype(int)

(df_corona_merged.loc[~matched, ['City_agas_code', 'town']]
    .drop_duplicates()
    .to_csv('/home/bcrlab/igguest/porat_naama/data/processed/unmatched_keys.csv', index=False, encoding='utf-8-sig'))

KeyError: 'pop'

In [ ]:
# --- inspect the unmatched keys ---
unmatched = (df_corona_merged.loc[df_corona_merged['has_census'] == 0]
             .groupby(['City_agas_code', 'town'], as_index=False)
             .agg(n_rows=('date', 'size'),
                  first_date=('date', 'min'),
                  last_date=('date', 'max'),
                  total_positive=('positive_daily', 'sum')))

# split the key back into its parts
unmatched['LocalityCode'] = unmatched['City_agas_code'].str.split('_').str[0]
unmatched['StatArea']     = unmatched['City_agas_code'].str.split('_').str[1]

# failure type: is the city missing from the census, or just this statistical area?
census_localities = set(df_mifkad['City_agas_code'].str.split('_').str[0])
unmatched['fail_type'] = unmatched['LocalityCode'].map(
    lambda l: 'locality_missing' if l not in census_localities else 'area_missing')

print(f'unmatched keys: {len(unmatched)}')
print(unmatched['fail_type'].value_counts(), '\n')

# which cities lose the most - these are the ones worth chasing
by_city = (unmatched.groupby(['LocalityCode', 'town', 'fail_type'], as_index=False)
           .agg(n_areas_lost=('City_agas_code', 'size'), n_rows=('n_rows', 'sum'))
           .sort_values('n_rows', ascending=False))
print(by_city.head(20).to_string(index=False))

unmatched.sort_values(['LocalityCode', 'StatArea']).to_csv(
    'unmatched_keys_detail.csv', index=False, encoding='utf-8-sig')

unmatched keys: 460
area_missing    460
Name: fail_type, dtype: int64

LocalityCode               town    fail_type  n_areas_lost  n_rows
        3000            ירושלים area_missing            63   73962
        5000        תל אביב-יפו area_missing            54   63396
        6400            הרצלייה area_missing            25   29350
        6900            כפר סבא area_missing            24   28176
          70              אשדוד area_missing            21   24654
        6500               חדרה area_missing            20   23480
        2610            בית שמש area_missing            19   22306
        1200 מודיעין-מכבים-רעות area_missing            16   18784
        6100            בני ברק area_missing            14   16436
        8600             רמת גן area_missing            10   11740
        7900          פתח תקווה area_missing            10   11740
        1161                רהט area_missing            10   11740
        6600              חולון area_missing            10   11740
        9000            באר שבע area_missing            10   11740
        8300        ראשון לציון area_missing            10   10936
        7800     פרדס חנה-כרכור area_missing             9   10566
        3616        מעלה אדומים area_missing             9   10566
        9500       קריית ביאליק area_missing             9   10566
        2660               יבנה area_missing             8    9392
        2640           ראש העין area_missing             8    9392

In [ ]:
# do these after merge:

# merged_df['percent_vaccinated_first_dose'] = (merged_df['accumulated_vaccination_first_dose'] / merged_df['pop'])*100
# merged_df['percent_vaccinated_second_dose'] = (merged_df['accumulated_vaccination_second_dose'] / merged_df['pop'])*100
# merged_df['percent_vaccinated_third_dose'] = (merged_df['accumulated_vaccination_third_dose'] / merged_df['pop'])*100
# merged_df.tail(20)